on: create
name: build and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: tag-filter
        run: |
          pattern="refs/tags/v${1:-*}"
          case "$GITHUB_REF" in
            "")
              echo "\$GITHUB_REF is not set"
              exit 1
              ;;
            $pattern)
              echo "$GITHUB_REF matches $pattern"
              echo "version:" "${GITHUB_REF#refs/tags/v}"
              exit 0
              ;;
            *)
              echo "This workflow only executes on version tags. $GITHUB_REF does not match $pattern"
              exit 78
          esac
      - uses: actions/checkout@master
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t gcr.io/jackfletch/website-frontend:${GITHUB_REF#refs/tags/v} .
      - name: gcloud auth
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: gcloud auth configure-docker
        uses: actions/gcloud/cli@master
        with:
          args: auth configure-docker --quiet
      - name: gcloud docker push
        uses: actions/gcloud/cli@master
        with:
          args: docker -- push gcr.io/jackfletch/website-frontend:${GITHUB_REF#refs/tags/v}
